require("plugins")
require("settings")
require("generals")
require("configs.Alpha")
require("configs.Autopairs")
require("configs.Colorizer")
require("configs.Colorscheme")
-- -- require("configs.Comment")
require("configs.Git")
require("configs.Illuminate")
require("configs.Impatient")
require("configs.Indentline")
-- require("configs.LSP")
require("configs.Neoscroll")
require("configs.Nvim-Notify")
require("configs.Nvim-Tree")
require("configs.Project")
-- -- require("configs.Renamer")
require("configs.Statusline")
require("configs.Surround")
require("configs.Telescope")
require("configs.Toggleterm")
require("configs.Treesitter")
require("configs.Web-Devicons")
require("configs.Whichkey")
require("configs.Zen-Mode")
