-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet
if vim.fn.has("nvim") == 1 then
	return {
		bufferline = {
			Error = "",
			Warning = "",
			Hint = "",
			Info = "",
		},
		diagnostics = {
			Error = "",
			Warning = "",
			Information = "",
			Question = "",
			Hint = "",
		},
		documents = {
			File = "",
			Files = "",
			Folder = "",
			OpenFolder = "",
		},
		git = {
			Add = "",
			Mod = "",
			Remove = "",
			Ignore = "",
			Rename = "",
			Diff = "",
			Repo = "",
		},
		kind = {
			Text = "",
			Method = "m",
			Function = "",
			Constructor = "",
			Field = "",
			-- Variable = "",
			Variable = "",
			Class = "",
			Interface = "",
			-- Module = "",
			Module = "",
			Property = "",
			Unit = "",
			Value = "",
			Enum = "",
			-- Keyword = "",
			Keyword = "",
			-- Snippet = "",
			Snippet = "",
			Color = "",
			File = "",
			Reference = "",
			Folder = "",
			EnumMember = "",
			Constant = "",
			Struct = "",
			Event = "",
			Operator = "",
			TypeParameter = "",
		},
		misc = {
			Robot = "ﮧ",
			Squirrel = "",
			Tag = "",
			Watch = "",
		},
		type = {
			Array = "",
			Number = "",
			String = "",
			Boolean = "蘒",
			Object = "",
		},
		ui = {
			Lock = "",
			Circle = "",
			BigCircle = "",
			BigUnfilledCircle = "",
			Close = "",
			NewFile = "",
			Search = "",
			Lightbulb = "",
			Project = "",
			Dashboard = "",
			History = "",
			Comment = "",
			Bug = "",
			Code = "",
			Telescope = "",
      Telescope_selection = " ",
			Gear = "",
			Package = "",
			List = "",
			SignIn = "",
			Check = "",
			Fire = "",
			Note = "",
			BookMark = "",
			Pencil = "",
			-- ChevronRight = "",
			ChevronRight = ">",
			Table = "",
			Calendar = "",
		},
	}
end
